version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        user: sail
        uid: 1000
    container_name: autt-app
    restart: unless-stopped
    working_dir: /var/www/html
    # Removi o volume do c√≥digo para evitar o erro de pasta vazia
    networks:
      - app-network
      - npm_network

  db:
    image: mysql:8.0
    container_name: autt-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: autet
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: sail
    volumes:
      - autt-db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  npm_network:
    external: true

volumes:
  autt-db-data:
    driver: local
